name: Release Helm Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"


      # Needed to avoid that cp-zookeeper can't be found
      - name: Skip kafka first
        run: |
          mkdir charts-kafka
          mv charts/cp-kafka charts-kafka

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          config: .github/cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser for Kafka
        uses: helm/chart-releaser-action@v1.2.1
        with:
          config: .github/cr.yaml
          charts_dir: charts-kafka
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
