name: Snyk scheduled Docker image scan for external dependencies

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:

  docker-images:
    runs-on: ubuntu-latest
    env:
      OUTPUT_FILE: workflows/docker-images-matrix.json
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.0

      - id: set-matrix
        name: Generate image matrix of current master branch
        env:
          # Any image that matches any of these patterns will be ignored for scanning.
          # Reasons:
          # ...
          EXCLUDE_IMAGE_PATTERNS: bin
          # Any chart name (dir name) in here will be ignored for scanning.
          # Reasons:
          # ...
          EXCLUDE_CHARTS:
        working-directory: .github/bin
        run: ./external_docker_image_matrix

      - name: Commit and push if docker_images_external.json changed
        run: |
          git diff
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add .github/workflows/docker_images_external.json
          git commit -am "Update docker image references in docker_images_external.json" || exit 0
          git push

  security:
    needs: docker-images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.docker-images.outputs.matrix) }}
    steps:
      - name: Run Snyk to check for vulnerabilities
        continue-on-error: true # To make sure that SARIF upload gets called
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ matrix.DOCKER_IMAGE }}
          args: >-
            --fail-on=upgradable
            --severity-threshold=high
            --policy-path=.snyk
            --org=radar-base
            --sarif-file-output=snyk.sarif

      # Detected vulnerabilities will appear on Github in Security->Code_scanning_alerts tab
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: ${{ matrix.DOCKER_IMAGE }}
          sarif_file: snyk.sarif
